/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "include/secp256k1.h"
/* Header for class org_bitcoin_NativeSecp256k1 */

#ifndef _Included_org_bitcoin_NativeSecp256k1
#define _Included_org_bitcoin_NativeSecp256k1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bitcoin_NativeSecp256k1
 * Method:    secp256k1_ctx_clone
 * Signature: (J)J
 */
JNIEXPORT jlong
JNICALL Java_network_minter_mintercore_crypto_NativeSecp256k1_secp256k1_ctx_clone
    (JNIEnv *, jclass, jlong);

/*
 * Class:     org_bitcoin_NativeSecp256k1
 * Method:    secp256k1_context_randomize
 * Signature: (Ljava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint
JNICALL Java_network_minter_mintercore_crypto_NativeSecp256k1_secp256k1_context_randomize
    (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_bitcoin_NativeSecp256k1
 * Method:    secp256k1_privkey_tweak_add
 * Signature: (Ljava/nio/ByteBuffer;J)[[B
 */
JNIEXPORT jobjectArray
JNICALL Java_network_minter_mintercore_crypto_NativeSecp256k1_secp256k1_privkey_tweak_1add
    (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_bitcoin_NativeSecp256k1
 * Method:    secp256k1_privkey_tweak_mul
 * Signature: (Ljava/nio/ByteBuffer;J)[[B
 */
JNIEXPORT jobjectArray
JNICALL Java_network_minter_mintercore_crypto_NativeSecp256k1_secp256k1_privkey_tweak_1mul
    (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_bitcoin_NativeSecp256k1
 * Method:    secp256k1_pubkey_tweak_add
 * Signature: (Ljava/nio/ByteBuffer;JI)[[B
 */
JNIEXPORT jobjectArray
JNICALL Java_network_minter_mintercore_crypto_NativeSecp256k1_secp256k1_pubkey_tweak_1add
    (JNIEnv *, jclass, jobject, jlong, jint);

/*
 * Class:     org_bitcoin_NativeSecp256k1
 * Method:    secp256k1_pubkey_tweak_mul
 * Signature: (Ljava/nio/ByteBuffer;JI)[[B
 */
JNIEXPORT jobjectArray
JNICALL Java_network_minter_mintercore_crypto_NativeSecp256k1_secp256k1_pubkey_tweak_1mul
    (JNIEnv *, jclass, jobject, jlong, jint);

/*
 * Class:     org_bitcoin_NativeSecp256k1
 * Method:    secp256k1_destroy_context
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_network_minter_mintercore_crypto_NativeSecp256k1_secp256k1_destroy_context
(JNIEnv * , jclass , jlong ) ;

/*
 * Class:     org_bitcoin_NativeSecp256k1
 * Method:    secp256k1_ecdsa_verify
 * Signature: (Ljava/nio/ByteBuffer;JII)I
 */
JNIEXPORT jint
JNICALL Java_network_minter_mintercore_crypto_NativeSecp256k1_secp256k1_ecdsa_verify
    (JNIEnv * , jclass, jobject, jlong, jint, jint);

/*
 * Class:     org_bitcoin_NativeSecp256k1
 * Method:    secp256k1_ecdsa_sign
 * Signature: (Ljava/nio/ByteBuffer;J)[[B
 */
JNIEXPORT jobjectArray
JNICALL Java_network_minter_mintercore_crypto_NativeSecp256k1_secp256k1_ecdsa_sign
    (JNIEnv * , jclass, jobject, jlong);

/*
 * Class:     org_bitcoin_NativeSecp256k1
 * Method:    secp256k1_ec_seckey_verify
 * Signature: (Ljava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint
JNICALL Java_network_minter_mintercore_crypto_NativeSecp256k1_secp256k1_ec_seckey_verify
    (JNIEnv * , jclass, jobject, jlong);

/*
 * Class:     org_bitcoin_NativeSecp256k1
 * Method:    secp256k1_ec_pubkey_create
 * Signature: (Ljava/nio/ByteBuffer;J)[[B
 */
JNIEXPORT jobjectArray
JNICALL Java_network_minter_mintercore_crypto_NativeSecp256k1_secp256k1_ec_pubkey_create
    (JNIEnv * , jclass, jobject, jlong);

/*
 * Class:     org_bitcoin_NativeSecp256k1
 * Method:    secp256k1_ec_pubkey_parse
 * Signature: (Ljava/nio/ByteBuffer;JI)[[B
 */
JNIEXPORT jobjectArray
JNICALL Java_network_minter_mintercore_crypto_NativeSecp256k1_secp256k1_ec_pubkey_parse
    (JNIEnv * , jclass, jobject, jlong, jint);

/*
 * Class:     org_bitcoin_NativeSecp256k1
 * Method:    secp256k1_ecdh
 * Signature: (Ljava/nio/ByteBuffer;JI)[[B
 */
JNIEXPORT jobjectArray
JNICALL Java_network_minter_mintercore_crypto_NativeSecp256k1_secp256k1_ecdh
    (JNIEnv * env, jclass
classObject , jobject byteBufferObject, jlong
ctx_l , jint publen ) ;

#ifdef __cplusplus
}
#endif
#endif
